// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifEgRSm3dN131CeLbRY3etkDWkxBU7TU',
    appId: '1:412531544268:web:83519978ec5cfd54277269',
    messagingSenderId: '412531544268',
    projectId: 'expanse-tracker-flutter',
    authDomain: 'expanse-tracker-flutter.firebaseapp.com',
    storageBucket: 'expanse-tracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8zLlofHFAX_nFCeNczKphv_2v7fDpJ3Q',
    appId: '1:412531544268:android:85d2cbd3a728979f277269',
    messagingSenderId: '412531544268',
    projectId: 'expanse-tracker-flutter',
    storageBucket: 'expanse-tracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD22V2Vp2F3HAJZ57g67fIsLghHruHxM6o',
    appId: '1:412531544268:ios:749148ec06245bbd277269',
    messagingSenderId: '412531544268',
    projectId: 'expanse-tracker-flutter',
    storageBucket: 'expanse-tracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.expanseTracker',
  );
}
